#!/usr/bin/env ruby
# frozen_string_literal: true

# Build Nginx config files with ERB template
require "erb"
require "fileutils"

def write_file!(filename, content)
  File.open(filename, "w") { |f| f.write(content) }
end

# Render ERB template
TEMPLATE_FILES = %w[nginx.conf bluedoc.conf]
TEMPLATE_FILES.each do |fname|
  file_path = File.expand_path(File.join(__FILE__, "../#{fname}.erb"))
  out_path = File.expand_path(File.join(__FILE__, "../#{fname}"))
  out = ERB.new(File.open(file_path).read).result
  write_file!(out_path, out)
end
